### ISSUE TITLE
website will not boot on Azure Webapps

### ISSUE THREAD

**Issue by molant** [murb/hashpash#1]
`index.js` is not getting the right value to work on that environment. It should be something like this:

``` javascript
var port = process.env.PORT || process.argv[2] || 8888;
```

**Comment by murb** [comment]
I guess Azure uses process.env.PORT; just pushed the option, hope it works now :)

**Comment by aarongustafson** [comment]
Still running into an issue. Here’s the log:

```
Fri Sep 23 2016 19:30:43 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
RangeError: "port" argument must be >= 0 and < 65536
    at assertPort (internal/net.js:17:11)
    at Server.listen (net.js:1384:5)
    at Object.<anonymous> (\\100.116.148.21\volume-22-default\fd67ea15a71fe3e488be\e3ec3589a2ba414ea07afaf6a81fe1fb\site\wwwroot\index.js:53:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
Application has thrown an uncaught exception and is terminated:
RangeError: "port" argument must be >= 0 and < 65536
    at assertPort (internal/net.js:17:11)
    at Server.listen (net.js:1384:5)
    at Object.<anonymous> (\\100.116.148.21\volume-22-default\fd67ea15a71fe3e488be\e3ec3589a2ba414ea07afaf6a81fe1fb\site\wwwroot\index.js:53:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
Fri Sep 23 2016 19:30:45 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
RangeError: "port" argument must be >= 0 and < 65536
    at assertPort (internal/net.js:17:11)
    at Server.listen (net.js:1384:5)
    at Object.<anonymous> (\\100.116.148.21\volume-22-default\fd67ea15a71fe3e488be\e3ec3589a2ba414ea07afaf6a81fe1fb\site\wwwroot\index.js:53:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
Application has thrown an uncaught exception and is terminated:
RangeError: "port" argument must be >= 0 and < 65536
    at assertPort (internal/net.js:17:11)
    at Server.listen (net.js:1384:5)
    at Object.<anonymous> (\\100.116.148.21\volume-22-default\fd67ea15a71fe3e488be\e3ec3589a2ba414ea07afaf6a81fe1fb\site\wwwroot\index.js:53:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

**Comment by aarongustafson** [comment]
I have synced with the latest btw: port fixes; and few language tweaks

**Comment by molant** [comment]
@aarongustafson I've fixed the issue in the Azure website. @murb the port in Azure is a string so it can't be `parseInt`. I've changed the final line to 

``` javascript
}).listen(port);
```

and it is working now. Problem will be if passing it as a parameter (fastest will be to remove that and just use 8888 or the Azure port).

**Comment by murb** [comment]
thanks for jumping in @molant, it's a bit hard to debug for me without azure! The parseint bit was just left by me from a minimalist (in the spirit of this competition) web server in node ;) apparently i simply should've made it even more minimal ;)
